version: '3.8'

services:
  # Database service
  db:
    image: mysql:5.7
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: appdb
      MYSQL_USER: appuser
      MYSQL_PASSWORD: password
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-network

  # Backend service (Node.js)
  backend:
    image: node:14
    container_name: node_backend
    working_dir: /app
    volumes:
      - ./backend:/app
    environment:
      DB_HOST: db
      DB_USER: appuser
      DB_PASS: password
      DB_NAME: appdb
    depends_on:
      - db
    command: sh -c "npm install && npm run start"
    networks:
      - app-network

  # Web server service (Nginx)
  web:
    image: nginx:alpine
    container_name: nginx_web
    volumes:
      - ./web:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"
    depends_on:
      - backend
    networks:
      - app-network

volumes:
  db_data:

networks:
  app-network:
    driver: bridge
